use std::path::Path;
use std::process::Command;

fn main() {
    generate_embedded_plugins();

    // Capture short commit hash for version-mismatch detection.
    // This ensures the daemon gets restarted when the binary changes,
    // even if the crate version (Cargo.toml) hasn't been bumped.
    let commit = Command::new("git")
        .args(["rev-parse", "--short=7", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=GIT_COMMIT={}", commit);

    // Use `git rev-parse --git-dir` to find the actual git metadata directory.
    // In a worktree, `.git` is a file pointing elsewhere (e.g.
    // `../../.git/worktrees/<name>`), so hard-coding `../../.git/HEAD` would
    // watch a path that doesn't exist and Cargo would never re-run this script.
    let git_dir = Command::new("git")
        .args(["rev-parse", "--git-dir"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string());

    if let Some(git_dir) = git_dir {
        // Re-run if git HEAD changes (detects branch switches).
        println!("cargo:rerun-if-changed={}/HEAD", git_dir);

        // Also track the ref that HEAD points to (detects new commits on the
        // current branch). When HEAD is "ref: refs/heads/main", new commits
        // update refs/heads/main but NOT HEAD itself.
        if let Ok(head) = std::fs::read_to_string(format!("{}/HEAD", git_dir)) {
            let head = head.trim();
            if let Some(refpath) = head.strip_prefix("ref: ") {
                // The ref itself may live in the common git dir (for worktrees,
                // that's the parent repo's .git), so check both locations.
                let common_dir = Command::new("git")
                    .args(["rev-parse", "--git-common-dir"])
                    .output()
                    .ok()
                    .and_then(|o| String::from_utf8(o.stdout).ok())
                    .map(|s| s.trim().to_string())
                    .unwrap_or_else(|| git_dir.clone());

                println!("cargo:rerun-if-changed={}/{}", git_dir, refpath);
                if common_dir != git_dir {
                    println!("cargo:rerun-if-changed={}/{}", common_dir, refpath);
                }

                // Packed-refs is updated when git packs loose refs or during
                // fetch/gc. A ref might only exist here, so track it too.
                println!("cargo:rerun-if-changed={}/packed-refs", common_dir);
            }
        }
    }
}

/// Generate the embedded_plugins module based on which plugin files exist.
/// If no plugins are built (clean checkout), generates an empty lookup.
fn generate_embedded_plugins() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    // Resolve absolute path for include_bytes! (works from any OUT_DIR location)
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let plugins_dir = Path::new(&manifest_dir).join("../runt-mcp/assets/plugins");

    let plugins: &[(&str, &str)] = &[
        ("plotly.js", "application/javascript; charset=utf-8"),
        ("vega.js", "application/javascript; charset=utf-8"),
        ("leaflet.js", "application/javascript; charset=utf-8"),
        ("leaflet.css", "text/css; charset=utf-8"),
    ];

    let mut arms = Vec::new();
    for (filename, content_type) in plugins {
        let path = plugins_dir.join(filename);
        if path.exists() {
            let abs_path = path.canonicalize().unwrap();
            let abs_str = abs_path.display();
            arms.push(format!(
                "        \"{filename}\" => Some((include_bytes!(\"{abs_str}\"), \"{content_type}\")),",
            ));
        }
        println!(
            "cargo:rerun-if-changed={}",
            plugins_dir.join(filename).display()
        );
    }

    let code = format!(
        "/// Look up an embedded renderer plugin asset by filename.\n\
         /// Returns (bytes, content_type) or None if the plugin isn't available.\n\
         /// Generated by build.rs — do not edit.\n\
         pub fn get(name: &str) -> Option<(&'static [u8], &'static str)> {{\n\
         \x20   match name {{\n\
         {}\n\
         \x20       _ => None,\n\
         \x20   }}\n\
         }}",
        arms.join("\n")
    );

    std::fs::write(Path::new(&out_dir).join("embedded_plugins.rs"), code).unwrap();
}
