//! Embedded renderer plugin assets for the MCP App.
//!
//! Heavy visualization renderers (plotly, vega, leaflet) are embedded in
//! the daemon binary via `include_bytes!` and served directly from memory
//! at `GET /plugins/{name}`. No disk deployment needed.
//!
//! The `get()` function is generated by `build.rs` based on which plugin
//! files exist in `crates/runt-mcp/assets/plugins/`. On a clean checkout
//! without running `pnpm build:plugins`, the lookup returns `None` for
//! all plugins (graceful degradation to text/plain fallback).

include!(concat!(env!("OUT_DIR"), "/embedded_plugins.rs"));
