packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-free'
  - esbuild
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  '@codemirror/language': 6.12.2
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
