/**
 * Renderer for application/vnd.imo.callout+json MIME type.
 */

const KIND_STYLES: Record<
  string,
  { border: string; bg: string; darkBg: string }
> = {
  neutral: { border: "#9ca3af", bg: "#f9fafb", darkBg: "#1f2937" },
  info: { border: "#3b82f6", bg: "#eff6ff", darkBg: "#1e3a5f" },
  warn: { border: "#f59e0b", bg: "#fffbeb", darkBg: "#422006" },
  success: { border: "#10b981", bg: "#ecfdf5", darkBg: "#064e3b" },
  danger: { border: "#ef4444", bg: "#fef2f2", darkBg: "#450a0a" },
};

export interface ImoCalloutData {
  content: string;
  kind: string;
}

export function ImoCallout({ data }: { data: ImoCalloutData }) {
  const kind = data.kind || "neutral";
  const style = KIND_STYLES[kind] || KIND_STYLES.neutral;
  const isDark = document.documentElement.classList.contains("dark");

  return (
    <div
      style={{
        borderLeft: `4px solid ${style.border}`,
        background: isDark ? style.darkBg : style.bg,
        padding: "12px 16px",
        borderRadius: "4px",
        margin: "4px 0",
        fontSize: "14px",
        lineHeight: "1.5",
        color: isDark ? "#e5e7eb" : "inherit",
      }}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: content is generated by imo Python library
      dangerouslySetInnerHTML={{ __html: data.content }}
    />
  );
}
