// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color theme for the notebook editor.
 */
export type ColorTheme = "classic" | "cream";
