// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Default packages for pixi environments.
 */
export type PixiDefaults = { default_packages: Array<string>, };
