// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CondaDefaults } from "./CondaDefaults";
import type { PixiDefaults } from "./PixiDefaults";
import type { PythonEnvType } from "./PythonEnvType";
import type { Runtime } from "./Runtime";
import type { ThemeMode } from "./ThemeMode";
import type { UvDefaults } from "./UvDefaults";

/**
 * Snapshot of all synced settings.
 */
export type SyncedSettings = { 
/**
 * UI theme
 */
theme: ThemeMode, 
/**
 * Default runtime for new notebooks
 */
default_runtime: Runtime, 
/**
 * Default Python environment type (uv or conda)
 */
default_python_env: PythonEnvType, 
/**
 * UV environment defaults
 */
uv: UvDefaults, 
/**
 * Conda environment defaults
 */
conda: CondaDefaults, 
/**
 * Pixi environment defaults
 */
pixi: PixiDefaults, 
/**
 * How long (in seconds) to keep notebook rooms alive after all clients disconnect.
 * This allows you to close and reopen the window without losing your kernel state.
 * Range: 5 seconds to 7 days (604800 seconds).
 */
keep_alive_secs: bigint, 
/**
 * Whether the user has completed the first-launch onboarding flow.
 * When false, the app shows the onboarding screen on startup.
 */
onboarding_completed: boolean, };
