/**
 * Fixture-based integration tests — real daemon-authored Automerge documents
 * loaded into WASM handles, synced through DirectTransport + SyncEngine.
 *
 * These fixtures are generated by `cargo test -p notebook-doc --test generate_fixtures`
 * and contain daemon-only mutations (outputs, execution counts) that can't be
 * done with WASM handles alone.
 *
 * Outputs follow the real protocol: the CRDT stores SHA-256 manifest hashes,
 * not raw JSON. Manifest files live in each fixture's blobs/ directory so
 * tests can resolve hashes to verify output content.
 *
 * The flow:
 * 1. Rust generates a NotebookDoc with daemon mutations → saves as doc.bin
 * 2. Manifest JSON for each output → hashed → hash stored in CRDT, JSON in blobs/
 * 3. This test loads doc.bin into a WASM server handle via Handle.load()
 * 4. A fresh WASM client syncs via DirectTransport (real 2-party Automerge sync)
 * 5. Assertions verify manifest hashes arrived, then resolve content from blobs/
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { VirtualAction, VirtualTimeScheduler } from "rxjs";
import { describe, expect, it } from "vite-plus/test";
import type { NotebookHandle } from "../../../apps/notebook/src/wasm/runtimed-wasm/runtimed_wasm";
import { DirectTransport, type ServerHandle } from "../src/direct-transport";
import type { SyncableHandle } from "../src/handle";
import { SyncEngine } from "../src/sync-engine";
import { initWasm } from "./wasm-harness";

// ── Fixture loading ──────────────────────────────────────────────────

const FIXTURES_DIR = resolve(__dirname, "fixtures");

const MANIFEST_HASH_RE = /^[a-f0-9]{64}$/;

interface ScenarioManifest {
  scenario: string;
  description: string;
  expected?: Record<string, unknown>;
  [key: string]: unknown;
}

function loadManifest(scenario: string): ScenarioManifest {
  const path = resolve(FIXTURES_DIR, scenario, "manifest.json");
  return JSON.parse(readFileSync(path, "utf-8"));
}

function loadDocBytes(scenario: string): Uint8Array {
  const path = resolve(FIXTURES_DIR, scenario, "doc.bin");
  return new Uint8Array(readFileSync(path));
}

function loadStateDocBytes(scenario: string): Uint8Array | null {
  const path = resolve(FIXTURES_DIR, scenario, "state_doc.bin");
  if (!existsSync(path)) return null;
  return new Uint8Array(readFileSync(path));
}

function loadBroadcastFrames(scenario: string): Uint8Array[] {
  const dir = resolve(FIXTURES_DIR, scenario);
  const files = readdirSync(dir)
    .filter((f) => f.startsWith("broadcast_") && f.endsWith(".bin"))
    .sort();
  return files.map((f) => new Uint8Array(readFileSync(resolve(dir, f))));
}

/** Resolve a manifest hash to its parsed JSON from the fixture's blobs/ dir. */
function resolveOutputManifest(scenario: string, hash: string): Record<string, unknown> {
  const blobPath = resolve(FIXTURES_DIR, scenario, "blobs", hash);
  if (!existsSync(blobPath)) {
    throw new Error(`Manifest blob not found: ${blobPath}`);
  }
  return JSON.parse(readFileSync(blobPath, "utf-8"));
}

/** Resolve an inline ContentRef to its string value. */
function resolveInline(contentRef: unknown): string {
  const r = contentRef as Record<string, unknown>;
  if ("inline" in r) return r.inline as string;
  throw new Error(`Expected inline ContentRef, got: ${JSON.stringify(contentRef)}`);
}

// ── WASM server handle adapter ──────────────────────────────────────

class WasmServerHandle implements ServerHandle {
  readonly handle: NotebookHandle;

  constructor(handle: NotebookHandle) {
    this.handle = handle;
  }

  flush_local_changes(): Uint8Array | null {
    return this.handle.flush_local_changes() ?? null;
  }

  receive_sync_message(message: Uint8Array): boolean {
    return this.handle.receive_sync_message(message);
  }

  reset_sync_state(): void {
    this.handle.reset_sync_state();
  }
}

// ── Test setup ──────────────────────────────────────────────────────

async function setupFixtureSync(scenario: string) {
  const Handle = await initWasm();
  const docBytes = loadDocBytes(scenario);
  const stateDocBytes = loadStateDocBytes(scenario);

  // Load the daemon-authored doc into a WASM server handle
  const server = Handle.load(docBytes);
  if (stateDocBytes) {
    server.load_state_doc(stateDocBytes);
  }
  const serverAdapter = new WasmServerHandle(server);

  // Fresh client — knows nothing, will learn via sync
  const client = Handle.create_bootstrap(`fixture-client-${Date.now()}`);
  if (stateDocBytes) {
    // Client also needs the state doc to read outputs via get_cell_outputs
    client.load_state_doc(stateDocBytes);
  }

  const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
  const transport = new DirectTransport(serverAdapter);
  const engine = new SyncEngine({
    getHandle: () => client as unknown as SyncableHandle,
    transport,
    scheduler,
  });

  async function startAndCompleteSync(): Promise<void> {
    engine.start();

    const syncComplete = new Promise<void>((resolve) => {
      const sub = engine.initialSyncComplete$.subscribe(() => {
        sub.unsubscribe();
        resolve();
      });
    });

    // Kick off the handshake
    engine.flush();

    // Run sync rounds until convergence
    for (let i = 0; i < 20; i++) {
      const pushed = transport.pushServerChanges();
      if (!pushed) break;
      await Promise.resolve();
    }

    await syncComplete;
  }

  return {
    server,
    client,
    engine,
    transport,
    scheduler,
    startAndCompleteSync,
    dispose() {
      engine.stop();
      server.free();
      client.free();
    },
  };
}

// ── Tests ────────────────────────────────────────────────────────────

describe("fixture-based integration: daemon-authored docs through WASM sync", () => {
  describe("output_streaming", () => {
    it("client receives manifest hashes for streamed outputs", async () => {
      const manifest = loadManifest("output_streaming");
      const h = await setupFixtureSync("output_streaming");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe(manifest.expected!.source as string);
      expect(h.client.get_cell_execution_count("cell-1")).toBe(
        manifest.expected!.execution_count as string,
      );

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(manifest.expected!.output_count as number);

      // Each output in the CRDT is a manifest hash, not raw JSON
      const expectedHashes = manifest.expected!.output_hashes as string[];
      for (let i = 0; i < outputs.length; i++) {
        expect(outputs[i]).toMatch(MANIFEST_HASH_RE);
        expect(outputs[i]).toBe(expectedHashes[i]);

        // Resolve hash → manifest → verify content
        const resolved = resolveOutputManifest("output_streaming", outputs[i]);
        expect(resolved.output_type).toBe("stream");
        expect(resolved.name).toBe("stdout");
        expect(resolveInline(resolved.text)).toBe(`${i}\n`);
      }

      h.dispose();
    });

    it("broadcasts arrive independently of sync frames", async () => {
      const broadcastFrames = loadBroadcastFrames("output_streaming");
      const h = await setupFixtureSync("output_streaming");

      await h.startAndCompleteSync();

      const broadcasts: unknown[] = [];
      const sub = h.engine.broadcasts$.subscribe((p) => broadcasts.push(p));

      for (const frame of broadcastFrames) {
        h.transport.deliver(Array.from(frame));
      }

      expect(broadcasts.length).toBe(3);
      for (const b of broadcasts) {
        const payload = b as Record<string, unknown>;
        expect(payload.event).toBe("output");
        expect(payload.cell_id).toBe("cell-1");
        expect(payload.output_type).toBe("stream");
        // output_json is the manifest hash, not raw JSON
        expect(payload.output_json).toMatch(MANIFEST_HASH_RE);
      }

      sub.unsubscribe();
      h.dispose();
    });
  });

  describe("execution_with_error", () => {
    it("client receives error manifest hash after sync", async () => {
      const h = await setupFixtureSync("execution_with_error");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(1);
      expect(h.client.get_cell_source("cell-1")).toBe("1 / 0");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);
      expect(outputs[0]).toMatch(MANIFEST_HASH_RE);

      // Resolve and verify error content
      const resolved = resolveOutputManifest("execution_with_error", outputs[0]);
      expect(resolved.output_type).toBe("error");
      expect(resolved.ename).toBe("ZeroDivisionError");
      expect(resolved.evalue).toBe("division by zero");

      // Traceback is inlined as a JSON array string
      const traceback = JSON.parse(resolveInline(resolved.traceback));
      expect(traceback.length).toBe(2);
      expect(traceback[1]).toContain("ZeroDivisionError");

      h.dispose();
    });
  });

  describe("re_execution", () => {
    it("client sees only second execution output hash after sync", async () => {
      const manifest = loadManifest("re_execution");
      const h = await setupFixtureSync("re_execution");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("2");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);
      expect(outputs[0]).toMatch(MANIFEST_HASH_RE);

      const expectedHashes = manifest.expected!.output_hashes as string[];
      expect(outputs[0]).toBe(expectedHashes[0]);

      // Resolve and verify it's the second execution's result
      const resolved = resolveOutputManifest("re_execution", outputs[0]);
      expect(resolved.output_type).toBe("execute_result");
      expect(resolved.execution_count).toBe(2);

      const data = resolved.data as Record<string, unknown>;
      expect(resolveInline(data["text/plain"])).toBe("42");

      h.dispose();
    });
  });

  describe("multi_cell_execution", () => {
    it("client receives all cells with correct execution state", async () => {
      const h = await setupFixtureSync("multi_cell_execution");

      await h.startAndCompleteSync();

      expect(h.client.cell_count()).toBe(3);

      // cell-1: code, executed, no outputs
      expect(h.client.get_cell_type("cell-1")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");
      const cell1Outputs = h.client.get_cell_outputs("cell-1") as string[] | undefined;
      expect(cell1Outputs ?? []).toHaveLength(0);

      // cell-2: code, executed, one output (manifest hash)
      expect(h.client.get_cell_type("cell-2")).toBe("code");
      expect(h.client.get_cell_execution_count("cell-2")).toBe("2");
      const cell2Outputs = h.client.get_cell_outputs("cell-2") as string[];
      expect(cell2Outputs.length).toBe(1);
      expect(cell2Outputs[0]).toMatch(MANIFEST_HASH_RE);

      // Resolve and verify stream content
      const resolved = resolveOutputManifest("multi_cell_execution", cell2Outputs[0]);
      expect(resolved.output_type).toBe("stream");
      expect(resolveInline(resolved.text)).toBe("42\n");

      // cell-3: markdown, no execution
      expect(h.client.get_cell_type("cell-3")).toBe("markdown");
      expect(h.client.get_cell_source("cell-3")).toBe("# Results");

      h.dispose();
    });
  });

  describe("display_data_output", () => {
    it("client receives manifest hash with mixed content refs", async () => {
      const h = await setupFixtureSync("display_data_output");

      await h.startAndCompleteSync();

      expect(h.client.get_cell_execution_count("cell-1")).toBe("1");

      const outputs = h.client.get_cell_outputs("cell-1") as string[];
      expect(outputs.length).toBe(1);
      expect(outputs[0]).toMatch(MANIFEST_HASH_RE);

      // Resolve manifest — has inlined text/plain and blob-ref image/png
      const resolved = resolveOutputManifest("display_data_output", outputs[0]);
      expect(resolved.output_type).toBe("display_data");

      const data = resolved.data as Record<string, unknown>;
      expect(resolveInline(data["text/plain"])).toBe("<Figure size 640x480>");

      // image/png is a blob ref (not inline)
      const imageRef = data["image/png"] as Record<string, unknown>;
      expect(imageRef.blob).toBeDefined();
      expect(imageRef.size).toBe(12345);

      h.dispose();
    });
  });

  describe("changeset emission from daemon-authored docs", () => {
    it("emits changesets when incremental daemon changes arrive", async () => {
      const Handle = await initWasm();
      const docBytes = loadDocBytes("output_streaming");

      const server = Handle.load(docBytes);
      const serverAdapter = new WasmServerHandle(server);

      const client = Handle.create_bootstrap(`fixture-changeset-${Date.now()}`);
      const scheduler = new VirtualTimeScheduler(VirtualAction, Infinity);
      const transport = new DirectTransport(serverAdapter);
      const engine = new SyncEngine({
        getHandle: () => client as unknown as SyncableHandle,
        transport,
        scheduler,
      });

      // Start and complete initial sync
      engine.start();
      const syncComplete = new Promise<void>((resolve) => {
        const sub = engine.initialSyncComplete$.subscribe(() => {
          sub.unsubscribe();
          resolve();
        });
      });
      engine.flush();
      for (let i = 0; i < 20; i++) {
        if (!transport.pushServerChanges()) break;
        await Promise.resolve();
      }
      await syncComplete;

      // Subscribe to changesets and make an incremental server change
      const changesets: unknown[] = [];
      const sub = engine.cellChanges$.subscribe((cs) => changesets.push(cs));

      server.update_source("cell-1", "print('changed')");
      transport.pushServerChanges();

      // Advance past coalescing window
      const target = scheduler.frame + 50;
      scheduler.maxFrames = target;
      scheduler.schedule(() => {}, 50);
      scheduler.flush();

      expect(changesets.length).toBeGreaterThan(0);

      sub.unsubscribe();
      engine.stop();
      server.free();
      client.free();
    });
  });
});
