/**
 * Bokeh Renderer Plugin
 *
 * On-demand renderer plugin for Bokeh visualization outputs.
 * Bundles BokehJS directly — evaluates UMD bundles to set window.Bokeh.
 *
 * Unlike Plotly/Vega plugins which render JSON specs, Bokeh outputs are
 * rendered by JavaScript code generated by the Python side. This plugin
 * makes BokehJS available as window.Bokeh so that the existing
 * application/javascript output handler can execute Bokeh's rendering code.
 *
 * Loaded into the isolated iframe via the renderer plugin API.
 */

// Raw UMD bundles — imported as strings via the vite-plugin-isolated-renderer
// raw-resolve mapping. Evaluated in install() to set up window.Bokeh.
import bokehCore from "bokeh-core-raw";
import bokehWidgets from "bokeh-widgets-raw";
import bokehTables from "bokeh-tables-raw";
import bokehApi from "bokeh-api-raw";
import bokehGl from "bokeh-gl-raw";

/**
 * Evaluate a BokehJS UMD bundle in the global scope.
 *
 * BokehJS UMD wrappers use `(function(root, factory) { ... })(this, ...)`
 * where `this` must be `window` for the library to set window.Bokeh.
 * Using `new Function(code).call(window)` provides the correct binding.
 */
function evalBokehBundle(code: string, label: string): void {
  try {
    new Function(code).call(window);
  } catch (err) {
    console.error(`[bokeh-renderer] Failed to evaluate ${label}:`, err);
  }
}

// --- Plugin install ---

export function install(_ctx: {
  register: (
    mimeTypes: string[],
    component: React.ComponentType<unknown>,
  ) => void;
}) {
  // Evaluate BokehJS bundles in order: core first, then extensions.
  // Core sets window.Bokeh; extensions call Bokeh.register_plugin().
  evalBokehBundle(bokehCore, "bokeh-core");
  evalBokehBundle(bokehWidgets, "bokeh-widgets");
  evalBokehBundle(bokehTables, "bokeh-tables");
  evalBokehBundle(bokehApi, "bokeh-api");
  evalBokehBundle(bokehGl, "bokeh-gl");

  // No React component registration needed. Bokeh rendering is handled by
  // the application/javascript output handler — the JS generated by Python's
  // bokeh.io.show() calls window.Bokeh.embed.embed_items_notebook().
}
