"""Type stubs for the runtimed native extension module (PyO3).

Auto-maintained — regenerate from crates/runtimed-py/src/ when the Rust API changes.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator, Coroutine, Iterator
from typing import Any

# ---------------------------------------------------------------------------
# Exception
# ---------------------------------------------------------------------------

class RuntimedError(Exception):
    """Error raised by runtimed operations."""

    ...

# ---------------------------------------------------------------------------
# Data classes (output types)
# ---------------------------------------------------------------------------

class Output:
    """A single output from cell execution."""

    @property
    def output_type(self) -> str:
        """Output type: "stream", "display_data", "execute_result", "error"."""
        ...

    @property
    def name(self) -> str | None:
        """For stream outputs: "stdout" or "stderr"."""
        ...

    @property
    def text(self) -> str | None:
        """For stream outputs: the text content."""
        ...

    @property
    def data(self) -> dict[str, str] | None:
        """For display_data/execute_result: mime type -> content."""
        ...

    @property
    def ename(self) -> str | None:
        """For errors: exception name."""
        ...

    @property
    def evalue(self) -> str | None:
        """For errors: exception value."""
        ...

    @property
    def traceback(self) -> list[str] | None:
        """For errors: traceback lines."""
        ...

    @property
    def execution_count(self) -> int | None:
        """For execute_result: execution count."""
        ...

class Cell:
    """A cell from the automerge document."""

    @property
    def id(self) -> str: ...
    @property
    def cell_type(self) -> str:
        """Cell type: "code", "markdown", or "raw"."""
        ...

    @property
    def position(self) -> str:
        """Fractional index hex string for ordering."""
        ...

    @property
    def source(self) -> str:
        """Cell source code/content."""
        ...

    @property
    def execution_count(self) -> int | None: ...
    @property
    def outputs(self) -> list[Output]: ...
    @property
    def metadata_json(self) -> str:
        """Cell metadata as JSON string."""
        ...

    @property
    def metadata(self) -> Any:
        """Parsed metadata dict."""
        ...

    @property
    def is_source_hidden(self) -> bool: ...
    @property
    def is_outputs_hidden(self) -> bool: ...
    @property
    def is_collapsed(self) -> bool: ...
    @property
    def tags(self) -> list[str]: ...

class ExecutionEvent:
    """An event from streaming cell execution."""

    @property
    def event_type(self) -> str:
        """Event type: "execution_started", "output", "done", "error", "kernel_status"."""
        ...

    @property
    def cell_id(self) -> str: ...
    @property
    def output(self) -> Output | None:
        """The output (only for "output" events, None in signal-only mode)."""
        ...

    @property
    def output_index(self) -> int | None:
        """Index of the output in the cell's outputs list."""
        ...

    @property
    def execution_count(self) -> int | None:
        """Execution count (only for "execution_started" events)."""
        ...

    @property
    def error_message(self) -> str | None:
        """Error message (only for "error" events)."""
        ...

class ExecutionResult:
    """Result of executing code."""

    @property
    def cell_id(self) -> str: ...
    @property
    def outputs(self) -> list[Output]: ...
    @property
    def success(self) -> bool: ...
    @property
    def execution_count(self) -> int | None: ...
    @property
    def stdout(self) -> str:
        """Combined stdout text."""
        ...

    @property
    def stderr(self) -> str:
        """Combined stderr text."""
        ...

    @property
    def display_data(self) -> list[Output]:
        """Display data outputs (display_data and execute_result)."""
        ...

    @property
    def error(self) -> Output | None:
        """Error output if any."""
        ...

class CompletionItem:
    """A single completion item from the kernel."""

    @property
    def label(self) -> str: ...
    @property
    def kind(self) -> str | None:
        """Kind: "function", "variable", "class", "module", etc."""
        ...

    @property
    def detail(self) -> str | None:
        """Short type annotation."""
        ...

    @property
    def source(self) -> str | None:
        """Source: "kernel"."""
        ...

class CompletionResult:
    """Result of a code completion request."""

    @property
    def items(self) -> list[CompletionItem]: ...
    @property
    def cursor_start(self) -> int: ...
    @property
    def cursor_end(self) -> int: ...

class QueueState:
    """Current state of the execution queue."""

    @property
    def executing(self) -> str | None:
        """Cell ID currently executing (None if idle)."""
        ...

    @property
    def queued(self) -> list[str]:
        """Cell IDs waiting in queue."""
        ...

class HistoryEntry:
    """A single entry from kernel input history."""

    @property
    def session(self) -> int: ...
    @property
    def line(self) -> int: ...
    @property
    def source(self) -> str: ...

class SyncEnvironmentResult:
    """Result of syncing environment with metadata."""

    @property
    def success(self) -> bool: ...
    @property
    def synced_packages(self) -> list[str]: ...
    @property
    def error(self) -> str | None: ...
    @property
    def needs_restart(self) -> bool: ...

class NotebookConnectionInfo:
    """Connection info returned when opening or creating a notebook."""

    @property
    def protocol(self) -> str: ...
    @property
    def protocol_version(self) -> int | None: ...
    @property
    def daemon_version(self) -> str | None: ...
    @property
    def notebook_id(self) -> str: ...
    @property
    def cell_count(self) -> int: ...
    @property
    def needs_trust_approval(self) -> bool: ...

# ---------------------------------------------------------------------------
# Iterator / stream types
# ---------------------------------------------------------------------------

class ExecutionEventStream:
    """Async iterator over execution events for a cell."""

    def __aiter__(self) -> AsyncIterator[ExecutionEvent]: ...
    def __anext__(self) -> Coroutine[Any, Any, ExecutionEvent]: ...

class ExecutionEventIterator:
    """Sync iterator over execution events for a cell."""

    def __iter__(self) -> Iterator[ExecutionEvent]: ...
    def __next__(self) -> ExecutionEvent: ...

class EventSubscription:
    """Async subscription to notebook broadcasts."""

    def __aiter__(self) -> AsyncIterator[ExecutionEvent]: ...
    def __anext__(self) -> Coroutine[Any, Any, ExecutionEvent]: ...
    def close(self) -> Coroutine[Any, Any, None]: ...

class EventIteratorSubscription:
    """Sync subscription to notebook broadcasts."""

    def __iter__(self) -> Iterator[ExecutionEvent]: ...
    def __next__(self) -> ExecutionEvent: ...
    def close(self) -> None: ...

# ---------------------------------------------------------------------------
# DaemonClient
# ---------------------------------------------------------------------------

class DaemonClient:
    """Client for communicating with the runtimed daemon."""

    def __init__(self) -> None: ...
    def ping(self) -> bool: ...
    def is_running(self) -> bool: ...
    def status(self) -> dict[str, Any]: ...
    def list_rooms(self) -> list[dict[str, Any]]: ...
    def flush_pool(self) -> None: ...
    def shutdown(self) -> None: ...

# ---------------------------------------------------------------------------
# Session (synchronous)
# ---------------------------------------------------------------------------

class Session:
    """Synchronous session for notebook interaction."""

    def __init__(
        self,
        notebook_id: str | None = None,
        peer_label: str | None = None,
    ) -> None: ...
    @property
    def notebook_id(self) -> str: ...
    @property
    def is_connected(self) -> bool: ...
    @property
    def kernel_started(self) -> bool: ...
    @property
    def kernel_type(self) -> str | None: ...
    @property
    def env_source(self) -> str | None: ...
    @property
    def connection_info(self) -> NotebookConnectionInfo | None: ...
    @staticmethod
    def open_notebook(
        path: str,
        peer_label: str | None = None,
    ) -> Session: ...
    @staticmethod
    def create_notebook(
        runtime: str = "python",
        working_dir: str | None = None,
        peer_label: str | None = None,
    ) -> Session: ...
    def connect(self) -> None: ...

    # Kernel lifecycle
    def start_kernel(
        self,
        kernel_type: str = "python",
        env_source: str = "auto",
        notebook_path: str | None = None,
    ) -> None: ...
    def shutdown_kernel(self) -> None: ...
    def restart_kernel(self, wait_for_ready: bool = True) -> list[str]: ...
    def interrupt(self) -> None: ...

    # Cell operations
    def create_cell(
        self,
        source: str = "",
        cell_type: str = "code",
        index: int | None = None,
    ) -> str:
        """Create a new cell.

        Args:
            source: Cell source text.
            cell_type: One of "code", "markdown", "raw".
            index: Position to insert. ``None`` appends at the end,
                ``0`` prepends at the beginning.

        Returns:
            The new cell's ID.
        """
        ...
    def set_source(self, cell_id: str, source: str) -> None: ...
    def append_source(self, cell_id: str, text: str) -> None: ...
    def set_cell_type(self, cell_id: str, cell_type: str) -> None: ...
    def get_cell(self, cell_id: str) -> Cell: ...
    def get_cells(self) -> list[Cell]: ...
    def get_cell_source(self, cell_id: str) -> str | None: ...
    def get_cell_type(self, cell_id: str) -> str | None: ...
    def get_cell_outputs(self, cell_id: str) -> list[str] | None: ...
    def get_cell_execution_count(self, cell_id: str) -> str | None: ...
    def get_cell_ids(self) -> list[str]: ...
    def get_cell_position(self, cell_id: str) -> str | None: ...
    def delete_cell(self, cell_id: str) -> None: ...
    def move_cell(self, cell_id: str, after_cell_id: str | None = None) -> str: ...
    def clear_outputs(self, cell_id: str) -> None: ...

    # Presence
    def get_peers(self) -> list[tuple[str, str]]: ...
    def get_remote_cursors(self) -> list[tuple[str, str, str, int, int]]: ...
    def set_cursor(self, cell_id: str, line: int, column: int) -> None: ...
    def set_selection(
        self,
        cell_id: str,
        anchor_line: int,
        anchor_col: int,
        head_line: int,
        head_col: int,
    ) -> None: ...

    # Save / Metadata
    def save(self, path: str | None = None) -> str: ...
    def set_metadata(self, key: str, value: str) -> None: ...
    def get_metadata(self, key: str) -> str | None: ...
    def set_kernelspec(
        self,
        name: str,
        display_name: str,
        language: str | None = None,
    ) -> None: ...
    def get_kernelspec(self) -> dict[str, str] | None: ...

    # Cell metadata
    def get_cell_metadata(self, cell_id: str) -> str | None: ...
    def set_cell_metadata(self, cell_id: str, metadata_json: str) -> bool: ...
    def update_cell_metadata_at(
        self,
        cell_id: str,
        path: list[str],
        value_json: str,
    ) -> bool: ...
    def set_cell_source_hidden(self, cell_id: str, hidden: bool) -> bool: ...
    def set_cell_outputs_hidden(self, cell_id: str, hidden: bool) -> bool: ...
    def set_cell_tags(self, cell_id: str, tags: list[str]) -> bool: ...

    # Dependencies
    def get_uv_dependencies(self) -> list[str]: ...
    def add_uv_dependency(self, package: str) -> None: ...
    def remove_uv_dependency(self, package: str) -> bool: ...
    def get_conda_dependencies(self) -> list[str]: ...
    def add_conda_dependency(self, package: str) -> None: ...
    def remove_conda_dependency(self, package: str) -> bool: ...
    def get_metadata_env_type(self) -> str | None: ...
    def get_settings(self) -> dict[str, Any] | None: ...

    # Execution
    def execute_cell(
        self,
        cell_id: str,
        timeout_secs: float = 60.0,
    ) -> ExecutionResult: ...
    def run(self, code: str, timeout_secs: float = 60.0) -> ExecutionResult: ...
    def queue_cell(self, cell_id: str) -> None: ...
    def stream_execute(
        self,
        cell_id: str,
        timeout_secs: float = 60.0,
        signal_only: bool = False,
    ) -> ExecutionEventIterator: ...
    def subscribe(
        self,
        cell_ids: list[str] | None = None,
        event_types: list[str] | None = None,
    ) -> EventIteratorSubscription: ...

    # Environment sync
    def sync_environment(self) -> SyncEnvironmentResult: ...

    # Completion, history, queue
    def complete(self, code: str, cursor_pos: int) -> CompletionResult: ...
    def get_history(
        self,
        pattern: str | None = None,
        n: int = 100,
        unique: bool = True,
    ) -> list[HistoryEntry]: ...
    def get_queue_state(self) -> QueueState: ...
    def run_all_cells(self) -> int: ...

    # Context manager
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: Any = None,
    ) -> bool: ...

# ---------------------------------------------------------------------------
# AsyncSession
# ---------------------------------------------------------------------------

class AsyncSession:
    """Async session for notebook interaction."""

    def __init__(
        self,
        notebook_id: str | None = None,
        peer_label: str | None = None,
    ) -> None: ...
    @property
    def notebook_id(self) -> str: ...
    def is_connected(self) -> Coroutine[Any, Any, bool]: ...
    def kernel_started(self) -> Coroutine[Any, Any, bool]: ...
    def kernel_type(self) -> Coroutine[Any, Any, str | None]: ...
    def env_source(self) -> Coroutine[Any, Any, str | None]: ...
    def connection_info(self) -> Coroutine[Any, Any, NotebookConnectionInfo | None]: ...
    @staticmethod
    def open_notebook(
        path: str,
        peer_label: str | None = None,
    ) -> Coroutine[Any, Any, AsyncSession]: ...
    @staticmethod
    def create_notebook(
        runtime: str = "python",
        working_dir: str | None = None,
        peer_label: str | None = None,
    ) -> Coroutine[Any, Any, AsyncSession]: ...
    def connect(self) -> Coroutine[Any, Any, None]: ...

    # Kernel lifecycle
    def start_kernel(
        self,
        kernel_type: str = "python",
        env_source: str = "auto",
        notebook_path: str | None = None,
    ) -> Coroutine[Any, Any, None]: ...
    def shutdown_kernel(self) -> Coroutine[Any, Any, None]: ...
    def restart_kernel(self, wait_for_ready: bool = True) -> Coroutine[Any, Any, list[str]]: ...
    def interrupt(self) -> Coroutine[Any, Any, None]: ...

    # Cell operations
    def create_cell(
        self,
        source: str = "",
        cell_type: str = "code",
        index: int | None = None,
    ) -> Coroutine[Any, Any, str]:
        """Create a new cell.

        Args:
            source: Cell source text.
            cell_type: One of "code", "markdown", "raw".
            index: Position to insert. ``None`` appends at the end,
                ``0`` prepends at the beginning.

        Returns:
            The new cell's ID.
        """
        ...
    def set_source(self, cell_id: str, source: str) -> Coroutine[Any, Any, None]: ...
    def append_source(self, cell_id: str, text: str) -> Coroutine[Any, Any, None]: ...
    def set_cell_type(self, cell_id: str, cell_type: str) -> Coroutine[Any, Any, None]: ...
    def get_cell(self, cell_id: str) -> Coroutine[Any, Any, Cell]: ...
    def get_cells(self) -> Coroutine[Any, Any, list[Cell]]: ...
    def get_cell_source(self, cell_id: str) -> Coroutine[Any, Any, str | None]: ...
    def get_cell_type(self, cell_id: str) -> Coroutine[Any, Any, str | None]: ...
    def get_cell_outputs(self, cell_id: str) -> Coroutine[Any, Any, list[str] | None]: ...
    def get_cell_execution_count(self, cell_id: str) -> Coroutine[Any, Any, str | None]: ...
    def get_cell_ids(self) -> Coroutine[Any, Any, list[str]]: ...
    def get_cell_position(self, cell_id: str) -> Coroutine[Any, Any, str | None]: ...
    def delete_cell(self, cell_id: str) -> Coroutine[Any, Any, None]: ...
    def move_cell(
        self, cell_id: str, after_cell_id: str | None = None
    ) -> Coroutine[Any, Any, str]: ...
    def clear_outputs(self, cell_id: str) -> Coroutine[Any, Any, None]: ...

    # Presence
    def get_peers(self) -> Coroutine[Any, Any, list[tuple[str, str]]]: ...
    def get_remote_cursors(
        self,
    ) -> Coroutine[Any, Any, list[tuple[str, str, str, int, int]]]: ...
    def set_cursor(self, cell_id: str, line: int, column: int) -> Coroutine[Any, Any, None]: ...
    def set_selection(
        self,
        cell_id: str,
        anchor_line: int,
        anchor_col: int,
        head_line: int,
        head_col: int,
    ) -> Coroutine[Any, Any, None]: ...

    # Save / Metadata
    def save(self, path: str | None = None) -> Coroutine[Any, Any, str]: ...
    def set_metadata(self, key: str, value: str) -> Coroutine[Any, Any, None]: ...
    def get_metadata(self, key: str) -> Coroutine[Any, Any, str | None]: ...
    def set_kernelspec(
        self,
        name: str,
        display_name: str,
        language: str | None = None,
    ) -> Coroutine[Any, Any, None]: ...
    def get_kernelspec(self) -> Coroutine[Any, Any, dict[str, str] | None]: ...

    # Cell metadata
    def get_cell_metadata(self, cell_id: str) -> Coroutine[Any, Any, str | None]: ...
    def set_cell_metadata(self, cell_id: str, metadata_json: str) -> Coroutine[Any, Any, bool]: ...
    def update_cell_metadata_at(
        self,
        cell_id: str,
        path: list[str],
        value_json: str,
    ) -> Coroutine[Any, Any, bool]: ...
    def set_cell_source_hidden(self, cell_id: str, hidden: bool) -> Coroutine[Any, Any, bool]: ...
    def set_cell_outputs_hidden(self, cell_id: str, hidden: bool) -> Coroutine[Any, Any, bool]: ...
    def set_cell_tags(self, cell_id: str, tags: list[str]) -> Coroutine[Any, Any, bool]: ...

    # Dependencies
    def get_uv_dependencies(self) -> Coroutine[Any, Any, list[str]]: ...
    def add_uv_dependency(self, package: str) -> Coroutine[Any, Any, None]: ...
    def remove_uv_dependency(self, package: str) -> Coroutine[Any, Any, bool]: ...
    def get_conda_dependencies(self) -> Coroutine[Any, Any, list[str]]: ...
    def add_conda_dependency(self, package: str) -> Coroutine[Any, Any, None]: ...
    def remove_conda_dependency(self, package: str) -> Coroutine[Any, Any, bool]: ...
    def get_metadata_env_type(self) -> Coroutine[Any, Any, str | None]: ...
    def get_settings(self) -> dict[str, Any] | None: ...

    # Execution
    def execute_cell(
        self,
        cell_id: str,
        timeout_secs: float = 60.0,
    ) -> Coroutine[Any, Any, ExecutionResult]: ...
    def run(
        self, code: str, timeout_secs: float = 60.0
    ) -> Coroutine[Any, Any, ExecutionResult]: ...
    def queue_cell(self, cell_id: str) -> Coroutine[Any, Any, None]: ...
    def stream_execute(
        self,
        cell_id: str,
        timeout_secs: float = 60.0,
        signal_only: bool = False,
    ) -> Coroutine[Any, Any, ExecutionEventStream]: ...
    def subscribe(
        self,
        cell_ids: list[str] | None = None,
        event_types: list[str] | None = None,
    ) -> EventSubscription: ...

    # Environment sync
    def sync_environment(self) -> Coroutine[Any, Any, SyncEnvironmentResult]: ...

    # Completion, history, queue
    def complete(self, code: str, cursor_pos: int) -> Coroutine[Any, Any, CompletionResult]: ...
    def get_history(
        self,
        pattern: str | None = None,
        n: int = 100,
        unique: bool = True,
    ) -> Coroutine[Any, Any, list[HistoryEntry]]: ...
    def get_queue_state(self) -> Coroutine[Any, Any, QueueState]: ...
    def run_all_cells(self) -> Coroutine[Any, Any, int]: ...

    # Context manager
    def close(self) -> Coroutine[Any, Any, None]: ...
    async def __aenter__(self) -> AsyncSession: ...
    async def __aexit__(
        self,
        _exc_type: type[BaseException] | None = None,
        _exc_val: BaseException | None = None,
        _exc_tb: Any = None,
    ) -> bool: ...

# ---------------------------------------------------------------------------
# Standalone functions
# ---------------------------------------------------------------------------

def show_notebook_app(
    notebook_path: str | os.PathLike[str] | None = None,
) -> None:
    """Launch the desktop notebook app, optionally opening a specific notebook."""
    ...

def default_socket_path() -> str:
    """Get the default daemon socket path.

    Respects the RUNTIMED_SOCKET_PATH environment variable if set.
    """
    ...
